import uuid
from datetime import datetime
from sqlalchemy import ForeignKey, Float, String, Text, Boolean, Integer, Enum as SAEnum, DateTime
from sqlalchemy.orm import Mapped, mapped_column
from backend.app.db.base import Base
from backend.app.models.policy_item import ReviewStatus
import enum


class AnswerScaleType(str, enum.Enum):
    likert_5 = "likert_5"
    binary = "binary"
    tradeoff = "tradeoff"


class Question(Base):
    __tablename__ = "questions"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    policy_item_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("policy_items.id"), nullable=True, index=True
    )
    # Root questions are topic-level entry points in the question tree.
    # They have is_root_question=True and topic_id set.
    # Follow-up questions (is_root_question=False) are adaptive and policy-item-level.
    is_root_question: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    topic_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("topics.id"), nullable=True, index=True
    )
    question_text_he: Mapped[str] = mapped_column(Text, nullable=False)
    question_text_en: Mapped[str] = mapped_column(Text, nullable=False)
    question_text_ru: Mapped[str | None] = mapped_column(Text, nullable=True)
    answer_scale_type: Mapped[AnswerScaleType] = mapped_column(
        SAEnum(AnswerScaleType, name="answer_scale_type", create_type=False),
        default=AnswerScaleType.likert_5,
    )
    neutrality_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    complexity_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    llm_prompt_version: Mapped[str | None] = mapped_column(String(50), nullable=True)
    # answer_polarity: +1.0 means "Strongly support" on the question = +1 on the policy axis.
    # -1.0 means the question is phrased in the OPPOSITE direction to the axis
    # (e.g. "Should Haredim serve?" → support=+1 but axis is haredi_service: +1=exempt).
    # The answers API multiplies answer_value by answer_polarity before storage.
    answer_polarity: Mapped[float] = mapped_column(Float, nullable=False, default=1.0)
    human_review_status: Mapped[ReviewStatus] = mapped_column(
        SAEnum(ReviewStatus, name="question_review_status", create_type=False),
        default=ReviewStatus.draft,
    )

    # ── Question-tree / graph fields (question bank) ───────────────────────────
    # parent_question_id: FK to another question. NULL for root/standalone questions.
    # Forms a tree where root questions branch into policy-item questions which
    # branch further into deep directional follow-ups.
    parent_question_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("questions.id"), nullable=True, index=True
    )
    # Tree depth: 0 = topic root, 1 = policy-item follow-up, 2 = deep directional drill-down
    tree_depth: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    # Optional: answer threshold that makes this question relevant as a follow-up.
    # E.g. trigger_answer_min=0.5 means "only ask if the parent answer >= +0.5 (strong support)".
    # Both NULL = always relevant as a follow-up (no trigger condition).
    trigger_answer_min: Mapped[float | None] = mapped_column(Float, nullable=True)
    trigger_answer_max: Mapped[float | None] = mapped_column(Float, nullable=True)
    # Subtopic tag: a finer-grained label within the topic (e.g. "haredi_draft" within "military_service")
    subtopic_tag: Mapped[str | None] = mapped_column(String(100), nullable=True)
    # When this question was generated by the LLM (for staleness tracking)
    generation_date: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    # Stale flag: set to True when the question references outdated events/facts.
    # Stale questions are hidden from the live questionnaire but kept in DB for audit.
    is_stale: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
