"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { getBill, BillDetail } from "@/lib/api";
import { useLang } from "@/lib/i18n";

export default function BillDetailPage() {
  const { id } = useParams<{ id: string }>();
  const { lang } = useLang();
  const [bill, setBill] = useState<BillDetail | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!id) return;
    getBill(id)
      .then(setBill)
      .catch(() => setError("Failed to load bill."))
      .finally(() => setLoading(false));
  }, [id]);

  if (loading) return (
    <div className="flex items-center gap-3 py-20 text-slate-500">
      <div className="h-6 w-6 rounded-full border-2 border-brand-500 border-t-transparent animate-spin" />
      Loading…
    </div>
  );
  if (error || !bill) return <p className="text-red-600 py-20">{error ?? "Not found"}</p>;

  const title = lang === "he" ? bill.title_he : (bill.title_en ?? bill.title_he);
  const summary = lang === "he" ? (bill.summary_he ?? bill.summary_en) : (bill.summary_en ?? bill.summary_he);

  return (
    <div className="space-y-8 pb-16">
      <Link href="/parties" className="text-sm text-brand-600 hover:underline">← Parties</Link>

      <div className="space-y-1">
        <p className="text-xs font-medium text-slate-500 uppercase tracking-wide">Bill</p>
        <h1 className="text-2xl font-bold text-slate-900 leading-snug">{title}</h1>
        {bill.title_en && lang !== "en" && (
          <p className="text-slate-400 text-sm">{bill.title_en}</p>
        )}
        <div className="flex flex-wrap gap-3 text-sm text-slate-500">
          {bill.date_submitted && <span>Submitted: {bill.date_submitted}</span>}
          {bill.status && <span className="capitalize">Status: {bill.status}</span>}
        </div>
        {bill.source_url && (
          <a
            href={bill.source_url}
            target="_blank"
            rel="noopener noreferrer"
            className="text-xs text-brand-600 hover:underline"
          >
            Source ↗
          </a>
        )}
        {bill.full_text_url && (
          <a
            href={bill.full_text_url}
            target="_blank"
            rel="noopener noreferrer"
            className="ms-4 text-xs text-brand-600 hover:underline"
          >
            Full text ↗
          </a>
        )}
      </div>

      {summary && (
        <section className="rounded-xl border border-slate-200 bg-white px-5 py-4 space-y-2">
          <h2 className="text-sm font-semibold text-slate-700">Summary</h2>
          <p className="text-sm text-slate-700 leading-relaxed">{summary}</p>
          <p className="text-xs text-slate-400">
            This summary was generated by an LLM and is subject to human review.
          </p>
        </section>
      )}
    </div>
  );
}

