"""add_root_question_and_backup

Revision ID: 0c6f3edc9944
Revises: e2269a930b25
Create Date: 2026-05-06 17:33:43.208312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c6f3edc9944'
down_revision: Union[str, None] = 'e2269a930b25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add is_root_question nullable first so existing rows don't violate NOT NULL,
    # then backfill False for all existing rows, then set the NOT NULL constraint.
    op.add_column('questions', sa.Column('is_root_question', sa.Boolean(), nullable=True))
    op.execute("UPDATE questions SET is_root_question = FALSE WHERE is_root_question IS NULL")
    op.alter_column('questions', 'is_root_question', nullable=False)

    op.add_column('questions', sa.Column('topic_id', sa.Uuid(), nullable=True))
    op.alter_column('questions', 'policy_item_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_questions_topic_id'), 'questions', ['topic_id'], unique=False)
    op.create_foreign_key(None, 'questions', 'topics', ['topic_id'], ['id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_index(op.f('ix_questions_topic_id'), table_name='questions')
    op.alter_column('questions', 'policy_item_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('questions', 'topic_id')
    op.drop_column('questions', 'is_root_question')
    # ### end Alembic commands ###

