"""add_user_skipped_questions

Revision ID: 9bfbadd706ed
Revises: g1h2i3j4k5l6
Create Date: 2026-05-09 16:28:35.765725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bfbadd706ed'
down_revision: Union[str, None] = 'g1h2i3j4k5l6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_questions_parent_question_id'), 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'questions', ['parent_question_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_questions_parent_question_id'), 'questions', 'questions', ['parent_question_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

