"""add_simulation_tables

Revision ID: e2269a930b25
Revises: 0c562b9360f6
Create Date: 2026-05-05 21:37:56.323342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2269a930b25'
down_revision: Union[str, None] = '0c562b9360f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_election_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('election_cycle', sa.String(length=20), nullable=False),
    sa.Column('election_date', sa.Date(), nullable=False),
    sa.Column('turnout', sa.Float(), nullable=True),
    sa.Column('threshold_percent', sa.Float(), nullable=True),
    sa.Column('total_valid_votes', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pollsters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('historical_bias_json', sa.JSON(), nullable=False),
    sa.Column('historical_error_std_json', sa.JSON(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('data_cutoff_date', sa.Date(), nullable=True),
    sa.Column('n_iterations', sa.Integer(), nullable=True),
    sa.Column('assumptions_json', sa.JSON(), nullable=False),
    sa.Column('input_snapshot_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coalition_scenarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('simulation_run_id', sa.UUID(), nullable=False),
    sa.Column('scenario_name', sa.String(length=200), nullable=False),
    sa.Column('probability_estimate', sa.Float(), nullable=True),
    sa.Column('seat_mean', sa.Float(), nullable=True),
    sa.Column('seat_p10', sa.Float(), nullable=True),
    sa.Column('seat_p90', sa.Float(), nullable=True),
    sa.Column('feasibility_score', sa.Float(), nullable=True),
    sa.Column('stability_score', sa.Float(), nullable=True),
    sa.Column('ideological_coherence_score', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('polls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pollster_id', sa.UUID(), nullable=False),
    sa.Column('field_start_date', sa.Date(), nullable=True),
    sa.Column('field_end_date', sa.Date(), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('population', sa.String(length=200), nullable=True),
    sa.Column('method', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['pollster_id'], ['pollsters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coalition_constraints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_party_instance_id', sa.UUID(), nullable=False),
    sa.Column('target_party_instance_id', sa.UUID(), nullable=True),
    sa.Column('target_bloc', sa.String(length=100), nullable=True),
    sa.Column('constraint_type', sa.String(length=50), nullable=False),
    sa.Column('strength', sa.String(length=10), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_refs_json', sa.JSON(), nullable=False),
    sa.Column('llm_explanation', sa.Text(), nullable=True),
    sa.Column('human_review_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['source_party_instance_id'], ['party_instances.id'], ),
    sa.ForeignKeyConstraint(['target_party_instance_id'], ['party_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coalition_scenario_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('party_instance_id', sa.UUID(), nullable=True),
    sa.Column('party_name', sa.String(length=200), nullable=False),
    sa.Column('expected_seats', sa.Float(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['party_instance_id'], ['party_instances.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['coalition_scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historical_party_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('historical_election_result_id', sa.UUID(), nullable=False),
    sa.Column('party_instance_id', sa.UUID(), nullable=True),
    sa.Column('reported_name', sa.String(length=200), nullable=False),
    sa.Column('vote_share', sa.Float(), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('passed_threshold', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['historical_election_result_id'], ['historical_election_results.id'], ),
    sa.ForeignKeyConstraint(['party_instance_id'], ['party_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poll_party_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('poll_id', sa.UUID(), nullable=False),
    sa.Column('party_instance_id', sa.UUID(), nullable=True),
    sa.Column('reported_name', sa.String(length=200), nullable=False),
    sa.Column('seats_mean', sa.Float(), nullable=True),
    sa.Column('vote_share_mean', sa.Float(), nullable=True),
    sa.Column('lower_bound', sa.Float(), nullable=True),
    sa.Column('upper_bound', sa.Float(), nullable=True),
    sa.Column('undecided_handling_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['party_instance_id'], ['party_instances.id'], ),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_party_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('simulation_run_id', sa.UUID(), nullable=False),
    sa.Column('party_instance_id', sa.UUID(), nullable=True),
    sa.Column('party_name', sa.String(length=200), nullable=False),
    sa.Column('seats_mean', sa.Float(), nullable=True),
    sa.Column('seats_median', sa.Float(), nullable=True),
    sa.Column('seats_p10', sa.Float(), nullable=True),
    sa.Column('seats_p25', sa.Float(), nullable=True),
    sa.Column('seats_p75', sa.Float(), nullable=True),
    sa.Column('seats_p90', sa.Float(), nullable=True),
    sa.Column('threshold_pass_probability', sa.Float(), nullable=True),
    sa.Column('vote_share_mean', sa.Float(), nullable=True),
    sa.Column('volatility_score', sa.Float(), nullable=True),
    sa.Column('is_new_party', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['party_instance_id'], ['party_instances.id'], ),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulation_party_results')
    op.drop_table('poll_party_results')
    op.drop_table('historical_party_results')
    op.drop_table('coalition_scenario_members')
    op.drop_table('coalition_constraints')
    op.drop_table('polls')
    op.drop_table('coalition_scenarios')
    op.drop_table('simulation_runs')
    op.drop_table('pollsters')
    op.drop_table('historical_election_results')
    # ### end Alembic commands ###

